/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFIACoin,
  IFIACoinInterface,
} from "../../../contracts/TestCaller.sol/IFIACoin";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    name: "protectedTransfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFIACoin__factory {
  static readonly abi = _abi;
  static createInterface(): IFIACoinInterface {
    return new Interface(_abi) as IFIACoinInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFIACoin {
    return new Contract(address, _abi, runner) as unknown as IFIACoin;
  }
}
