/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFIACoin__factory } from "./IFIACoin__factory";
export { TestCaller__factory } from "./TestCaller__factory";
