/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFIACoinV7,
  IFIACoinV7Interface,
} from "../../../contracts/FIACoinMigration.sol/IFIACoinV7";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "stakeCount",
        type: "uint256",
      },
    ],
    name: "migrateFromV6",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFIACoinV7__factory {
  static readonly abi = _abi;
  static createInterface(): IFIACoinV7Interface {
    return new Interface(_abi) as IFIACoinV7Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFIACoinV7 {
    return new Contract(address, _abi, runner) as unknown as IFIACoinV7;
  }
}
