/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FIACoinMigration__factory } from "./FIACoinMigration__factory";
export { IFIACoinV7__factory } from "./IFIACoinV7__factory";
