/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFIA__factory } from "./IFIA__factory";
export { TestProtectedCaller__factory } from "./TestProtectedCaller__factory";
