/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TestProtectedCallerInterface extends Interface {
  getFunction(
    nameOrSignature: "callTwice" | "reuseNonceInOneTx"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "callTwice",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reuseNonceInOneTx",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "callTwice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reuseNonceInOneTx",
    data: BytesLike
  ): Result;
}

export interface TestProtectedCaller extends BaseContract {
  connect(runner?: ContractRunner | null): TestProtectedCaller;
  waitForDeployment(): Promise<this>;

  interface: TestProtectedCallerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  callTwice: TypedContractMethod<
    [
      fia: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      n1: BigNumberish,
      n2: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  reuseNonceInOneTx: TypedContractMethod<
    [
      fia: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      nonce: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "callTwice"
  ): TypedContractMethod<
    [
      fia: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      n1: BigNumberish,
      n2: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reuseNonceInOneTx"
  ): TypedContractMethod<
    [
      fia: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      nonce: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
