/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FailingTargetInterface extends Interface {
  getFunction(
    nameOrSignature: "called" | "doSomething" | "willRevert"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "called", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "doSomething",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "willRevert",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "called", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "doSomething",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "willRevert", data: BytesLike): Result;
}

export interface FailingTarget extends BaseContract {
  connect(runner?: ContractRunner | null): FailingTarget;
  waitForDeployment(): Promise<this>;

  interface: FailingTargetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  called: TypedContractMethod<[], [boolean], "view">;

  doSomething: TypedContractMethod<[], [void], "payable">;

  willRevert: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "called"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "doSomething"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "willRevert"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
