/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governance from "./governance";
export type { governance };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as testing from "./testing";
export type { testing };
import type * as utils from "./utils";
export type { utils };
export type { FIACoinV6 } from "./FIACoinV6";
export type { FIACoinV6Upgradeable } from "./FIACoinV6Upgradeable";
export type { FIACoinV7Upgradeable } from "./FIACoinV7Upgradeable";
