/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lpTimelockSol from "./LPTimelock.sol";
export type { lpTimelockSol };
import type * as nftTimelockSol from "./NFTTimelock.sol";
export type { nftTimelockSol };
export type { FIACoin } from "./FIACoin";
