name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install
      run: npm ci
    - name: Compile
      run: npx hardhat compile
    - name: Test
      run: npx hardhat test

    - name: Deploy (optional)
      if: ${{ secrets.PRIVATE_KEY && secrets.RPC_BASE_SEPOLIA }}
      run: |
        npx hardhat run scripts/deploy.ts --network baseSepolia
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        RPC_BASE_SEPOLIA: ${{ secrets.RPC_BASE_SEPOLIA }}
        TREASURY_ADDR: ${{ secrets.TREASURY_ADDR }}
        FOUNDER_ADDR: ${{ secrets.FOUNDER_ADDR }}

    - name: Verify on BaseScan (optional)
      if: ${{ secrets.BASESCAN_API_KEY }}
      run: |
        ADDR=$(jq -r .address < deployments/fia.json)
        ARGS=$(jq -r '.args | map(tostring) | join(" ")' < deployments/fia.json)
        npx hardhat verify --network baseSepolia $ADDR $ARGS
      env:
        BASESCAN_API_KEY: ${{ secrets.BASESCAN_API_KEY }}
        RPC_BASE_SEPOLIA: ${{ secrets.RPC_BASE_SEPOLIA }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
