/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ReentrantReceiver,
  ReentrantReceiverInterface,
} from "../../../contracts/ReentrantReceiver.sol/ReentrantReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "attacker",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516101c33803806101c383398101604081905261002f9161005d565b600080546001600160a01b039092166001600160a01b0319928316179055600180549091163317905561008d565b60006020828403121561006f57600080fd5b81516001600160a01b038116811461008657600080fd5b9392505050565b6101278061009c6000396000f3fe60806040526004361060295760003560e01c806348eb76ee146099578063fc0c546a1460d357602f565b36602f57005b6000805460405163561b246360e01b81526001600482015262278d00602482015260448101929092526001600160a01b03169063561b246390606401600060405180830381600087803b158015608457600080fd5b505af11580156097573d6000803e3d6000fd5b005b34801560a457600080fd5b5060015460b7906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b34801560de57600080fd5b5060005460b7906001600160a01b03168156fea2646970667358221220ee2f6bc6610de13368edbe16da9e75532e12039b627a5361ffe4e11dd2b52dd564736f6c63430008140033";

type ReentrantReceiverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrantReceiverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrantReceiver__factory extends ContractFactory {
  constructor(...args: ReentrantReceiverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _token: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_token, overrides || {});
  }
  override deploy(
    _token: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_token, overrides || {}) as Promise<
      ReentrantReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReentrantReceiver__factory {
    return super.connect(runner) as ReentrantReceiver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrantReceiverInterface {
    return new Interface(_abi) as ReentrantReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReentrantReceiver {
    return new Contract(address, _abi, runner) as unknown as ReentrantReceiver;
  }
}
